apiVersion: 1

datasources:
  - name: event-log-mysql
    uid: mysql-event-log-pipeline
    type: mysql
    access: proxy
    url: mysql:3306
    user: event_user
    isDefault: true
    editable: false
    jsonData:
      database: event_log_pipeline
      maxOpenConns: 20
      maxIdleConns: 10
      maxIdleConnsAuto: false
      connMaxLifetime: 14400
    secureJsonData:
      password: event_password
